#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UmitEticaret")]
	public partial class EticaretDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCinsiyet(Cinsiyet instance);
    partial void UpdateCinsiyet(Cinsiyet instance);
    partial void DeleteCinsiyet(Cinsiyet instance);
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    partial void InsertMarka(Marka instance);
    partial void UpdateMarka(Marka instance);
    partial void DeleteMarka(Marka instance);
    partial void InsertUrun(Urun instance);
    partial void UpdateUrun(Urun instance);
    partial void DeleteUrun(Urun instance);
    partial void InsertUye(Uye instance);
    partial void UpdateUye(Uye instance);
    partial void DeleteUye(Uye instance);
    partial void InsertYonetici(Yonetici instance);
    partial void UpdateYonetici(Yonetici instance);
    partial void DeleteYonetici(Yonetici instance);
    partial void InsertYoneticiTipi(YoneticiTipi instance);
    partial void UpdateYoneticiTipi(YoneticiTipi instance);
    partial void DeleteYoneticiTipi(YoneticiTipi instance);
    #endregion
		
		public EticaretDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.UmitEticaretConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EticaretDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EticaretDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EticaretDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EticaretDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cinsiyet> Cinsiyets
		{
			get
			{
				return this.GetTable<Cinsiyet>();
			}
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		public System.Data.Linq.Table<Marka> Markas
		{
			get
			{
				return this.GetTable<Marka>();
			}
		}
		
		public System.Data.Linq.Table<Urun> Uruns
		{
			get
			{
				return this.GetTable<Urun>();
			}
		}
		
		public System.Data.Linq.Table<Uye> Uyes
		{
			get
			{
				return this.GetTable<Uye>();
			}
		}
		
		public System.Data.Linq.Table<Yonetici> Yoneticis
		{
			get
			{
				return this.GetTable<Yonetici>();
			}
		}
		
		public System.Data.Linq.Table<YoneticiTipi> YoneticiTipis
		{
			get
			{
				return this.GetTable<YoneticiTipi>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uyeekle")]
		public int uyeekle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string epos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string sif, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cins, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sifred, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string uguid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string gsoru, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cevap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string sonuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ad, epos, sif, cins, sifred, uguid, gsoru, cevap, sonuc, id);
			sonuc = ((string)(result.GetParameterValue(8)));
			id = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cinsiyet")]
	public partial class Cinsiyet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CinsiyetID;
		
		private string _CinsiyetAdi;
		
		private EntitySet<Uye> _Uyes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCinsiyetIDChanging(int value);
    partial void OnCinsiyetIDChanged();
    partial void OnCinsiyetAdiChanging(string value);
    partial void OnCinsiyetAdiChanged();
    #endregion
		
		public Cinsiyet()
		{
			this._Uyes = new EntitySet<Uye>(new Action<Uye>(this.attach_Uyes), new Action<Uye>(this.detach_Uyes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CinsiyetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CinsiyetID
		{
			get
			{
				return this._CinsiyetID;
			}
			set
			{
				if ((this._CinsiyetID != value))
				{
					this.OnCinsiyetIDChanging(value);
					this.SendPropertyChanging();
					this._CinsiyetID = value;
					this.SendPropertyChanged("CinsiyetID");
					this.OnCinsiyetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CinsiyetAdi", DbType="VarChar(10)")]
		public string CinsiyetAdi
		{
			get
			{
				return this._CinsiyetAdi;
			}
			set
			{
				if ((this._CinsiyetAdi != value))
				{
					this.OnCinsiyetAdiChanging(value);
					this.SendPropertyChanging();
					this._CinsiyetAdi = value;
					this.SendPropertyChanged("CinsiyetAdi");
					this.OnCinsiyetAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cinsiyet_Uye", Storage="_Uyes", ThisKey="CinsiyetID", OtherKey="Cinsiyet")]
		public EntitySet<Uye> Uyes
		{
			get
			{
				return this._Uyes;
			}
			set
			{
				this._Uyes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uyes(Uye entity)
		{
			this.SendPropertyChanging();
			entity.Cinsiyet1 = this;
		}
		
		private void detach_Uyes(Uye entity)
		{
			this.SendPropertyChanging();
			entity.Cinsiyet1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KategoriID;
		
		private string _KategoriAdi;
		
		private System.Nullable<int> _AnaKategoriID;
		
		private System.Nullable<int> _Aktiflik;
		
		private EntitySet<Urun> _Uruns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategoriIDChanging(int value);
    partial void OnKategoriIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    partial void OnAnaKategoriIDChanging(System.Nullable<int> value);
    partial void OnAnaKategoriIDChanged();
    partial void OnAktiflikChanging(System.Nullable<int> value);
    partial void OnAktiflikChanged();
    #endregion
		
		public Kategori()
		{
			this._Uruns = new EntitySet<Urun>(new Action<Urun>(this.attach_Uruns), new Action<Urun>(this.detach_Uruns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="VarChar(50)")]
		public string KategoriAdi
		{
			get
			{
				return this._KategoriAdi;
			}
			set
			{
				if ((this._KategoriAdi != value))
				{
					this.OnKategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._KategoriAdi = value;
					this.SendPropertyChanged("KategoriAdi");
					this.OnKategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnaKategoriID", DbType="Int")]
		public System.Nullable<int> AnaKategoriID
		{
			get
			{
				return this._AnaKategoriID;
			}
			set
			{
				if ((this._AnaKategoriID != value))
				{
					this.OnAnaKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._AnaKategoriID = value;
					this.SendPropertyChanged("AnaKategoriID");
					this.OnAnaKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiflik", DbType="Int")]
		public System.Nullable<int> Aktiflik
		{
			get
			{
				return this._Aktiflik;
			}
			set
			{
				if ((this._Aktiflik != value))
				{
					this.OnAktiflikChanging(value);
					this.SendPropertyChanging();
					this._Aktiflik = value;
					this.SendPropertyChanged("Aktiflik");
					this.OnAktiflikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Urun", Storage="_Uruns", ThisKey="KategoriID", OtherKey="KategoriID")]
		public EntitySet<Urun> Uruns
		{
			get
			{
				return this._Uruns;
			}
			set
			{
				this._Uruns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marka")]
	public partial class Marka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MarkaID;
		
		private string _MarkaAdi;
		
		private EntitySet<Urun> _Uruns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarkaIDChanging(int value);
    partial void OnMarkaIDChanged();
    partial void OnMarkaAdiChanging(string value);
    partial void OnMarkaAdiChanged();
    #endregion
		
		public Marka()
		{
			this._Uruns = new EntitySet<Urun>(new Action<Urun>(this.attach_Uruns), new Action<Urun>(this.detach_Uruns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MarkaID
		{
			get
			{
				return this._MarkaID;
			}
			set
			{
				if ((this._MarkaID != value))
				{
					this.OnMarkaIDChanging(value);
					this.SendPropertyChanging();
					this._MarkaID = value;
					this.SendPropertyChanged("MarkaID");
					this.OnMarkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAdi", DbType="VarChar(50)")]
		public string MarkaAdi
		{
			get
			{
				return this._MarkaAdi;
			}
			set
			{
				if ((this._MarkaAdi != value))
				{
					this.OnMarkaAdiChanging(value);
					this.SendPropertyChanging();
					this._MarkaAdi = value;
					this.SendPropertyChanged("MarkaAdi");
					this.OnMarkaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marka_Urun", Storage="_Uruns", ThisKey="MarkaID", OtherKey="MarkaID")]
		public EntitySet<Urun> Uruns
		{
			get
			{
				return this._Uruns;
			}
			set
			{
				this._Uruns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Marka = this;
		}
		
		private void detach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Marka = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urun")]
	public partial class Urun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunID;
		
		private string _UrunAdi;
		
		private System.Nullable<int> _StokMiktari;
		
		private System.Nullable<int> _KategoriID;
		
		private System.Nullable<int> _MarkaID;
		
		private string _UrunAciklama;
		
		private string _UrunResim;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<decimal> _VergiOran;
		
		private System.Nullable<int> _Aktiflik;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Marka> _Marka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnStokMiktariChanging(System.Nullable<int> value);
    partial void OnStokMiktariChanged();
    partial void OnKategoriIDChanging(System.Nullable<int> value);
    partial void OnKategoriIDChanged();
    partial void OnMarkaIDChanging(System.Nullable<int> value);
    partial void OnMarkaIDChanged();
    partial void OnUrunAciklamaChanging(string value);
    partial void OnUrunAciklamaChanged();
    partial void OnUrunResimChanging(string value);
    partial void OnUrunResimChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    partial void OnVergiOranChanging(System.Nullable<decimal> value);
    partial void OnVergiOranChanged();
    partial void OnAktiflikChanging(System.Nullable<int> value);
    partial void OnAktiflikChanged();
    #endregion
		
		public Urun()
		{
			this._Kategori = default(EntityRef<Kategori>);
			this._Marka = default(EntityRef<Marka>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="VarChar(500)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokMiktari", DbType="Int")]
		public System.Nullable<int> StokMiktari
		{
			get
			{
				return this._StokMiktari;
			}
			set
			{
				if ((this._StokMiktari != value))
				{
					this.OnStokMiktariChanging(value);
					this.SendPropertyChanging();
					this._StokMiktari = value;
					this.SendPropertyChanged("StokMiktari");
					this.OnStokMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", DbType="Int")]
		public System.Nullable<int> KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaID", DbType="Int")]
		public System.Nullable<int> MarkaID
		{
			get
			{
				return this._MarkaID;
			}
			set
			{
				if ((this._MarkaID != value))
				{
					if (this._Marka.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarkaIDChanging(value);
					this.SendPropertyChanging();
					this._MarkaID = value;
					this.SendPropertyChanged("MarkaID");
					this.OnMarkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAciklama", DbType="VarChar(MAX)")]
		public string UrunAciklama
		{
			get
			{
				return this._UrunAciklama;
			}
			set
			{
				if ((this._UrunAciklama != value))
				{
					this.OnUrunAciklamaChanging(value);
					this.SendPropertyChanging();
					this._UrunAciklama = value;
					this.SendPropertyChanged("UrunAciklama");
					this.OnUrunAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunResim", DbType="VarChar(100)")]
		public string UrunResim
		{
			get
			{
				return this._UrunResim;
			}
			set
			{
				if ((this._UrunResim != value))
				{
					this.OnUrunResimChanging(value);
					this.SendPropertyChanging();
					this._UrunResim = value;
					this.SendPropertyChanged("UrunResim");
					this.OnUrunResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiOran", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> VergiOran
		{
			get
			{
				return this._VergiOran;
			}
			set
			{
				if ((this._VergiOran != value))
				{
					this.OnVergiOranChanging(value);
					this.SendPropertyChanging();
					this._VergiOran = value;
					this.SendPropertyChanged("VergiOran");
					this.OnVergiOranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiflik", DbType="Int")]
		public System.Nullable<int> Aktiflik
		{
			get
			{
				return this._Aktiflik;
			}
			set
			{
				if ((this._Aktiflik != value))
				{
					this.OnAktiflikChanging(value);
					this.SendPropertyChanging();
					this._Aktiflik = value;
					this.SendPropertyChanged("Aktiflik");
					this.OnAktiflikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Urun", Storage="_Kategori", ThisKey="KategoriID", OtherKey="KategoriID", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.Uruns.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.Uruns.Add(this);
						this._KategoriID = value.KategoriID;
					}
					else
					{
						this._KategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marka_Urun", Storage="_Marka", ThisKey="MarkaID", OtherKey="MarkaID", IsForeignKey=true)]
		public Marka Marka
		{
			get
			{
				return this._Marka.Entity;
			}
			set
			{
				Marka previousValue = this._Marka.Entity;
				if (((previousValue != value) 
							|| (this._Marka.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marka.Entity = null;
						previousValue.Uruns.Remove(this);
					}
					this._Marka.Entity = value;
					if ((value != null))
					{
						value.Uruns.Add(this);
						this._MarkaID = value.MarkaID;
					}
					else
					{
						this._MarkaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Marka");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uye")]
	public partial class Uye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UyeID;
		
		private string _UyeAdiSoyadi;
		
		private string _Eposta;
		
		private string _Sifre;
		
		private System.Nullable<int> _Aktiflik;
		
		private System.Nullable<int> _Cinsiyet;
		
		private System.Nullable<int> _SifreDurumu;
		
		private string _UyeGuid;
		
		private string _GizliSoru;
		
		private string _Cevap;
		
		private EntityRef<Cinsiyet> _Cinsiyet1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUyeIDChanging(int value);
    partial void OnUyeIDChanged();
    partial void OnUyeAdiSoyadiChanging(string value);
    partial void OnUyeAdiSoyadiChanged();
    partial void OnEpostaChanging(string value);
    partial void OnEpostaChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnAktiflikChanging(System.Nullable<int> value);
    partial void OnAktiflikChanged();
    partial void OnCinsiyetChanging(System.Nullable<int> value);
    partial void OnCinsiyetChanged();
    partial void OnSifreDurumuChanging(System.Nullable<int> value);
    partial void OnSifreDurumuChanged();
    partial void OnUyeGuidChanging(string value);
    partial void OnUyeGuidChanged();
    partial void OnGizliSoruChanging(string value);
    partial void OnGizliSoruChanged();
    partial void OnCevapChanging(string value);
    partial void OnCevapChanged();
    #endregion
		
		public Uye()
		{
			this._Cinsiyet1 = default(EntityRef<Cinsiyet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UyeID
		{
			get
			{
				return this._UyeID;
			}
			set
			{
				if ((this._UyeID != value))
				{
					this.OnUyeIDChanging(value);
					this.SendPropertyChanging();
					this._UyeID = value;
					this.SendPropertyChanged("UyeID");
					this.OnUyeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeAdiSoyadi", DbType="VarChar(50)")]
		public string UyeAdiSoyadi
		{
			get
			{
				return this._UyeAdiSoyadi;
			}
			set
			{
				if ((this._UyeAdiSoyadi != value))
				{
					this.OnUyeAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._UyeAdiSoyadi = value;
					this.SendPropertyChanged("UyeAdiSoyadi");
					this.OnUyeAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eposta", DbType="VarChar(100)")]
		public string Eposta
		{
			get
			{
				return this._Eposta;
			}
			set
			{
				if ((this._Eposta != value))
				{
					this.OnEpostaChanging(value);
					this.SendPropertyChanging();
					this._Eposta = value;
					this.SendPropertyChanged("Eposta");
					this.OnEpostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="VarChar(100)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiflik", DbType="Int")]
		public System.Nullable<int> Aktiflik
		{
			get
			{
				return this._Aktiflik;
			}
			set
			{
				if ((this._Aktiflik != value))
				{
					this.OnAktiflikChanging(value);
					this.SendPropertyChanging();
					this._Aktiflik = value;
					this.SendPropertyChanged("Aktiflik");
					this.OnAktiflikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="Int")]
		public System.Nullable<int> Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					if (this._Cinsiyet1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifreDurumu", DbType="Int")]
		public System.Nullable<int> SifreDurumu
		{
			get
			{
				return this._SifreDurumu;
			}
			set
			{
				if ((this._SifreDurumu != value))
				{
					this.OnSifreDurumuChanging(value);
					this.SendPropertyChanging();
					this._SifreDurumu = value;
					this.SendPropertyChanged("SifreDurumu");
					this.OnSifreDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeGuid", DbType="VarChar(100)")]
		public string UyeGuid
		{
			get
			{
				return this._UyeGuid;
			}
			set
			{
				if ((this._UyeGuid != value))
				{
					this.OnUyeGuidChanging(value);
					this.SendPropertyChanging();
					this._UyeGuid = value;
					this.SendPropertyChanged("UyeGuid");
					this.OnUyeGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GizliSoru", DbType="VarChar(100)")]
		public string GizliSoru
		{
			get
			{
				return this._GizliSoru;
			}
			set
			{
				if ((this._GizliSoru != value))
				{
					this.OnGizliSoruChanging(value);
					this.SendPropertyChanging();
					this._GizliSoru = value;
					this.SendPropertyChanged("GizliSoru");
					this.OnGizliSoruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cevap", DbType="VarChar(30)")]
		public string Cevap
		{
			get
			{
				return this._Cevap;
			}
			set
			{
				if ((this._Cevap != value))
				{
					this.OnCevapChanging(value);
					this.SendPropertyChanging();
					this._Cevap = value;
					this.SendPropertyChanged("Cevap");
					this.OnCevapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cinsiyet_Uye", Storage="_Cinsiyet1", ThisKey="Cinsiyet", OtherKey="CinsiyetID", IsForeignKey=true)]
		public Cinsiyet Cinsiyet1
		{
			get
			{
				return this._Cinsiyet1.Entity;
			}
			set
			{
				Cinsiyet previousValue = this._Cinsiyet1.Entity;
				if (((previousValue != value) 
							|| (this._Cinsiyet1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cinsiyet1.Entity = null;
						previousValue.Uyes.Remove(this);
					}
					this._Cinsiyet1.Entity = value;
					if ((value != null))
					{
						value.Uyes.Add(this);
						this._Cinsiyet = value.CinsiyetID;
					}
					else
					{
						this._Cinsiyet = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cinsiyet1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yonetici")]
	public partial class Yonetici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YoneticiID;
		
		private string _YoneticiAdi;
		
		private string _YoneticiEposta;
		
		private string _Sifre;
		
		private System.Nullable<int> _YoneticiTipiID;
		
		private System.Nullable<int> _Aktiflik;
		
		private EntityRef<YoneticiTipi> _YoneticiTipi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYoneticiIDChanging(int value);
    partial void OnYoneticiIDChanged();
    partial void OnYoneticiAdiChanging(string value);
    partial void OnYoneticiAdiChanged();
    partial void OnYoneticiEpostaChanging(string value);
    partial void OnYoneticiEpostaChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnYoneticiTipiIDChanging(System.Nullable<int> value);
    partial void OnYoneticiTipiIDChanged();
    partial void OnAktiflikChanging(System.Nullable<int> value);
    partial void OnAktiflikChanged();
    #endregion
		
		public Yonetici()
		{
			this._YoneticiTipi = default(EntityRef<YoneticiTipi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YoneticiID
		{
			get
			{
				return this._YoneticiID;
			}
			set
			{
				if ((this._YoneticiID != value))
				{
					this.OnYoneticiIDChanging(value);
					this.SendPropertyChanging();
					this._YoneticiID = value;
					this.SendPropertyChanged("YoneticiID");
					this.OnYoneticiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiAdi", DbType="VarChar(50)")]
		public string YoneticiAdi
		{
			get
			{
				return this._YoneticiAdi;
			}
			set
			{
				if ((this._YoneticiAdi != value))
				{
					this.OnYoneticiAdiChanging(value);
					this.SendPropertyChanging();
					this._YoneticiAdi = value;
					this.SendPropertyChanged("YoneticiAdi");
					this.OnYoneticiAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiEposta", DbType="VarChar(100)")]
		public string YoneticiEposta
		{
			get
			{
				return this._YoneticiEposta;
			}
			set
			{
				if ((this._YoneticiEposta != value))
				{
					this.OnYoneticiEpostaChanging(value);
					this.SendPropertyChanging();
					this._YoneticiEposta = value;
					this.SendPropertyChanged("YoneticiEposta");
					this.OnYoneticiEpostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="VarChar(100)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiTipiID", DbType="Int")]
		public System.Nullable<int> YoneticiTipiID
		{
			get
			{
				return this._YoneticiTipiID;
			}
			set
			{
				if ((this._YoneticiTipiID != value))
				{
					if (this._YoneticiTipi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYoneticiTipiIDChanging(value);
					this.SendPropertyChanging();
					this._YoneticiTipiID = value;
					this.SendPropertyChanged("YoneticiTipiID");
					this.OnYoneticiTipiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiflik", DbType="Int")]
		public System.Nullable<int> Aktiflik
		{
			get
			{
				return this._Aktiflik;
			}
			set
			{
				if ((this._Aktiflik != value))
				{
					this.OnAktiflikChanging(value);
					this.SendPropertyChanging();
					this._Aktiflik = value;
					this.SendPropertyChanged("Aktiflik");
					this.OnAktiflikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YoneticiTipi_Yonetici", Storage="_YoneticiTipi", ThisKey="YoneticiTipiID", OtherKey="YoneticiTipiID", IsForeignKey=true)]
		public YoneticiTipi YoneticiTipi
		{
			get
			{
				return this._YoneticiTipi.Entity;
			}
			set
			{
				YoneticiTipi previousValue = this._YoneticiTipi.Entity;
				if (((previousValue != value) 
							|| (this._YoneticiTipi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._YoneticiTipi.Entity = null;
						previousValue.Yoneticis.Remove(this);
					}
					this._YoneticiTipi.Entity = value;
					if ((value != null))
					{
						value.Yoneticis.Add(this);
						this._YoneticiTipiID = value.YoneticiTipiID;
					}
					else
					{
						this._YoneticiTipiID = default(Nullable<int>);
					}
					this.SendPropertyChanged("YoneticiTipi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YoneticiTipi")]
	public partial class YoneticiTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YoneticiTipiID;
		
		private string _YoneticiTipiAdi;
		
		private EntitySet<Yonetici> _Yoneticis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYoneticiTipiIDChanging(int value);
    partial void OnYoneticiTipiIDChanged();
    partial void OnYoneticiTipiAdiChanging(string value);
    partial void OnYoneticiTipiAdiChanged();
    #endregion
		
		public YoneticiTipi()
		{
			this._Yoneticis = new EntitySet<Yonetici>(new Action<Yonetici>(this.attach_Yoneticis), new Action<Yonetici>(this.detach_Yoneticis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiTipiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YoneticiTipiID
		{
			get
			{
				return this._YoneticiTipiID;
			}
			set
			{
				if ((this._YoneticiTipiID != value))
				{
					this.OnYoneticiTipiIDChanging(value);
					this.SendPropertyChanging();
					this._YoneticiTipiID = value;
					this.SendPropertyChanged("YoneticiTipiID");
					this.OnYoneticiTipiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiTipiAdi", DbType="VarChar(50)")]
		public string YoneticiTipiAdi
		{
			get
			{
				return this._YoneticiTipiAdi;
			}
			set
			{
				if ((this._YoneticiTipiAdi != value))
				{
					this.OnYoneticiTipiAdiChanging(value);
					this.SendPropertyChanging();
					this._YoneticiTipiAdi = value;
					this.SendPropertyChanged("YoneticiTipiAdi");
					this.OnYoneticiTipiAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YoneticiTipi_Yonetici", Storage="_Yoneticis", ThisKey="YoneticiTipiID", OtherKey="YoneticiTipiID")]
		public EntitySet<Yonetici> Yoneticis
		{
			get
			{
				return this._Yoneticis;
			}
			set
			{
				this._Yoneticis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Yoneticis(Yonetici entity)
		{
			this.SendPropertyChanging();
			entity.YoneticiTipi = this;
		}
		
		private void detach_Yoneticis(Yonetici entity)
		{
			this.SendPropertyChanging();
			entity.YoneticiTipi = null;
		}
	}
}
#pragma warning restore 1591
